#!/usr/bin/python
import unittest, time
from selenium import webdriver
from pyvirtualdisplay import Display

class FTS3develSeTab(unittest.TestCase):

    def setUp(self):
        self.display = Display(visible=0, size=(800, 600))
        self.display.start()
        profile = webdriver.FirefoxProfile('/home/jenkins/.mozilla/firefox/browser/default/jenkins')
        self.driver = webdriver.Firefox(profile)

    def test_add_good_certificate(self):
        """
        Test adding new certificate 
        """
        driver = self.driver
        driver.get("https://fts3-devel.cern.ch:8446/config/authorize")

        input_list = ["/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=vpupkin/CN=000000/CN=Vasya Pupkin", 
                      "/C=RU/O=RDIG/OU=users/OU=ihep.su/CN=Misha Mishin", 
                      "/C=RU/O=RDIG/OU=users/OU=itep.ru/CN=Alexander Plushkin", 
                      "/C=RU/O=RDIG/OU=users/OU=jinr.ru/CN=Katya Maria Lomova"
                      ]

        for element in input_list:
            count = 0
            userdn_field = driver.find_element_by_id('authz-add-field-dn')
            userdn_field.clear()
            userdn_field.send_keys(element)

            button_add = driver.find_element_by_id('auth-add-frm-submit')
            button_add.click()
            time.sleep(1)

        #CHECK IF EVERYTHING WAS SAVED
        check0_list = []
        check1_list = []

        count = 0
        page_list = driver.find_elements_by_xpath('//span[@class="monospace"]')

        for elem in page_list:
            check0_list.append(elem.text)
        count = count + 1

        count = 0
        for element in input_list:
            check1_list.append(element)
        count = count + 1

        if not set(check1_list) < set(check0_list):
            return self.assertFalse("TEST: The static authorization wasn't saved", set(check1_list) - set(check0_list))


    def tearDown(self):
        self.driver.close()
        self.display.stop()

if __name__ == "__main__":
    unittest.main()

