#!/usr/bin/env python
from fts3.cli import Delegator
import logging
import sys
import traceback


if __name__ == "__main__":
    try:
        delegator = Delegator()
        delegator(sys.argv[1:])
    except Exception, e:
        logging.critical(str(e))
        if logging.getLogger().getEffectiveLevel() == logging.DEBUG:
            traceback.print_exc()
        sys.exit(1)
