#!/usr/bin/env python
from fts3.cli import Snapshot
import logging
import sys
import traceback


try:
    snapshot = Snapshot(sys.argv[1:])
    snapshot()
except Exception, e:
    logging.critical(str(e))
    if logging.getLogger().getEffectiveLevel() == logging.DEBUG:
        traceback.print_exc()
    sys.exit(1)
