#!/usr/bin/env python
from fts3.cli import WhoAmI
import logging
import sys
import traceback


try:
    whoami = WhoAmI()
    whoami(sys.argv[1:])
except Exception, e:
    logging.critical(str(e))
    if logging.getLogger().getEffectiveLevel() == logging.DEBUG:
        traceback.print_exc()
    sys.exit(1)
