#!/usr/bin/env python
from fts3.cli import Banning
import logging
import sys
import traceback


try:
    banning = Banning()
    banning(sys.argv[1:])
except Exception, e:
    logging.critical(str(e))
    if logging.getLogger().getEffectiveLevel() == logging.DEBUG:
        traceback.print_exc()
    sys.exit(1)
