#!/usr/bin/env python
from fts3.cli import ServerStatus
import logging
import sys
import traceback


if __name__ == "__main__":
    try:
        banning = ServerStatus()
        sys.exit(banning(sys.argv[1:]))
    except Exception, e:
        logging.critical(str(e))
        if logging.getLogger().getEffectiveLevel() == logging.DEBUG:
            traceback.print_exc()
        sys.exit(1)
