#!/usr/bin/python
import unittest, time, urllib
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from pyvirtualdisplay import Display

class FTS3develSeTab(unittest.TestCase):

    def setUp(self):
        self.display = Display(visible=0, size=(800, 600))
        self.display.start()
        profile = webdriver.FirefoxProfile('/home/jenkins/.mozilla/firefox/browser/default/jenkins')
        self.driver = webdriver.Firefox(profile)

    def test_save_bad_global(self):
        """
        Test save changes with wrong data
        """
        driver = self.driver
        driver.get("https://fts3-devel.cern.ch:8446/config/global")

        #SET UP
        setup_list = [
            ("badvo28", "0", "0", "0", "0", "true"),
            ("badvo29", "5", "15", "20", "25", "false"),
            ("badvo30", "10", "20", "30", "40", "false"),
            ("badvo31", "10", "20", "30", "40", "true"),
            ("badvo32", "0", "0", "0", "0", "true"),
            ("badvo33", "5", "15", "20", "25", "false"),
            ("badvo34", "10", "20", "30", "40", "true"),
            ("badvo35", "10", "20", "30", "40", "true"),
            ("badvo36", "0", "0", "0", "0", "true"),
            ("badvo37", "5", "15", "20", "25", "false"),
            ("badvo38", "10", "20", "30", "40", "false"),
            ("badvo39", "10", "20", "30", "40", "true"),
            ("badvo40", "0", "0", "0", "0", "true"),
            ("badvo41", "5", "15", "20", "25", "false"),
            ("badvo42", "10", "20", "30", "40", "false"),
            ("badvo43", "10", "20", "30", "40", "true"),
            ("badvo44", "0", "0", "0", "0", "true")
        ]

        for element in setup_list:

            voname_field = driver.find_element_by_id('vo-config-add-field-vo')
            voname_field.clear()
            voname_field.send_keys(element[0])

            retries_field = driver.find_element_by_id('retry')
            retries_field.clear()
            retries_field.send_keys(element[1])

            globaltimeout_field = driver.find_element_by_id('global_timeout')
            globaltimeout_field.clear()
            globaltimeout_field.send_keys(element[2])

            queue_field = driver.find_element_by_id('max_time_queue')
            queue_field.clear()
            queue_field.send_keys(element[3])

            addsec_field = driver.find_element_by_id('sec_per_mb')
            addsec_field.clear()
            addsec_field.send_keys(element[4])


            showdn_field = driver.find_element_by_xpath('//tbody[@id="vo-config-add"][tr/td/select[@id="show_user_dn"]]')
            if element[5] == 'false':
                showdn_field.click()
                options = showdn_field.find_elements_by_tag_name("option")
                for option in options:
                    if option.get_attribute("value") == 'false':
                        option.click()
            elif element[5] == 'true':
                showdn_field.click()
                options = showdn_field.find_elements_by_tag_name("option")
                for option in options:
                    if option.get_attribute("value") == 'true':
                        option.click()


            button_add = driver.find_element_by_id('button_add_global')
            button_add.click()
            time.sleep(1)

        driver.refresh()
        time.sleep(1)

        #CHECK IF EVERYTHING WAS SAVED
        check0_list = []
        check1_list = []

        count = 0
        page_list = driver.find_elements_by_xpath('//td[@class="vo_name"]')

        for elem in page_list:
            check0_list.append(elem.text)
        count = count + 1

        count = 0
        for element in setup_list:
            check1_list.append(element[0])
        count = count + 1

        if not set(check1_list) < set(check0_list):
            return self.assertFalse("SETUP: The retry wasn't saved", set(check1_list) - set(check0_list))

        #TEST test_save_bad_global
        input_list = [
            ("badvo28", "-1", "0", "0", "0", "true"),
            ("badvo29", "5", "-1", "20", "25", "false"),
            ("badvo30", "10", "20", "-1", "40", "false"),
            ("badvo31", "10", "20", "30", "-1", "true"),
            ("badvo32", "3.14", "0", "0", "0", "true"),
            ("badvo33", "5", "3.14", "20", "25", "false"),
            ("badvo34", "10", "20", "3.14", "40", "false"),
            ("badvo35", "10", "20", "30", "3.14", "true"),
            ("badvo36", "abc", "0", "0", "0", "true"),
            ("badvo37", "5", "abc", "20", "25", "false"),
            ("badvo38", "10", "20", "abc", "40", "false"),
            ("badvo39", "10", "20", "30", "abc", "true"),
            ("badvo40", "$", "0", "0", "0", "true"),
            ("badvo41", "5", "$", "20", "25", "false"),
            ("badvo42", "10", "20", "$", "40", "false"),
            ("badvo43", "10", "20", "30", "$", "true"),
            ("badvo44", "11", "0", "0", "0", "true")
        ]

        #SAVE 
        for element in input_list:
            count = 0
            tr_list = driver.find_elements_by_xpath('//tbody[@id="vo-config-list"]//tr')
            for tr in tr_list :
                if tr.get_attribute('name') == element[0]:   
                    retries_field =  driver.find_element_by_xpath('//tr[@name="'+element[0]+'"]//input[@name="retry"]')
                    retries_field.click()
                    retries_field.send_keys(Keys.CONTROL + 'a')
                    retries_field.send_keys(Keys.BACKSPACE)
                    retries_field.send_keys(element[1])

                    globaltimeout_field =  driver.find_element_by_xpath('//tr[@name="'+element[0]+'"]//input[@name="global_timeout"]')
                    globaltimeout_field.send_keys(Keys.CONTROL + 'a')
                    globaltimeout_field.send_keys(Keys.BACKSPACE)
                    globaltimeout_field.send_keys(element[2])

                    queue_field =  driver.find_element_by_xpath('//tr[@name="'+element[0]+'"]//input[@name="max_time_queue"]')
                    queue_field.send_keys(Keys.CONTROL + 'a')
                    queue_field.send_keys(Keys.BACKSPACE)
                    queue_field.send_keys(element[3])

                    addsec_field =  driver.find_element_by_xpath('//tr[@name="'+element[0]+'"]//input[@name="sec_per_mb"]')
                    addsec_field.send_keys(Keys.CONTROL + 'a')
                    addsec_field.send_keys(Keys.BACKSPACE)
                    addsec_field.send_keys(element[4])

                    if element[5] == 'false':
                        showdn_field =  driver.find_element_by_xpath('//tr[@name="'+element[0]+'"]//select[@name="show_user_dn"]')
                        showdn_field.click()
                        options = showdn_field.find_elements_by_tag_name("option")
                        for option in options:
                            if option.get_attribute("value") == 'false':
                                option.click()
                    elif element[5] == 'true':
                        showdn_field =  driver.find_element_by_xpath('//tr[@name="'+element[0]+'"]//select[@name="show_user_dn"]')
                        showdn_field.click()
                        options = showdn_field.find_elements_by_tag_name("option")
                        for option in options:
                            if option.get_attribute("value") == 'true':
                                option.click()

                    savebtn_list =  driver.find_element_by_xpath('//tr[@name="'+element[0]+'"]//button[@id="button_save_global"]')
                    savebtn_list.click()
                    time.sleep(1)
                    if not driver.find_element_by_xpath("//div[@class='modal-backdrop fade in']"):
                        pass
                    else:
                        alert = driver.find_element_by_xpath("//div[@class='modal-backdrop fade in']")
                        alert.click()
                count = count + 1


        #CHECK IF IT WAS SAVED
        check_list = []
        retr_list = driver.find_elements_by_xpath('//tbody[@id="vo-config-list"]//input[@name="retry"]')
        glob_list = driver.find_elements_by_xpath('//tbody[@id="vo-config-list"]//input[@name="global_timeout"]')
        queu_list = driver.find_elements_by_xpath('//tbody[@id="vo-config-list"]//input[@name="max_time_queue"]')
        adds_list = driver.find_elements_by_xpath('//tbody[@id="vo-config-list"]//input[@name="sec_per_mb"]')
        shdn_list = driver.find_elements_by_xpath('//tbody[@id="vo-config-list"]//select[@name="show_user_dn"]')
        for element in input_list:
            count = 0
            for r,g,q,a,s in zip(retr_list, glob_list, queu_list, adds_list, shdn_list):
                if r.get_attribute('value') == element[1] and  g.get_attribute('value')==element[2] and q.get_attribute('value')==element[3] and a.get_attribute('value')==element[4] and s.get_attribute('value')==element[5]:
                    check_list.append(element)	    
                count = count + 1

        if set(check_list)&set(input_list):
            return self.assertFalse("TEST: The changes were NOT saved", set(check_list)&set(input_list))

    def tearDown(self):
        self.driver.close()
        self.display.stop()

if __name__ == "__main__":
    unittest.main()

