#!/usr/bin/python
import unittest, time, urllib
from selenium import webdriver
from pyvirtualdisplay import Display

class FTS3develSeTab(unittest.TestCase):

    def setUp(self):
        self.display = Display(visible=0, size=(800, 600))
        self.display.start()
        profile = webdriver.FirefoxProfile('/home/jenkins/.mozilla/firefox/browser/default/jenkins')
        self.driver = webdriver.Firefox(profile)

    def test_add_good_global(self):
        """
        Test add retries with proper data
        """
        driver = self.driver
        driver.get("https://fts3-devel.cern.ch:8446/config/global")

        input_list = [
            ("*", "1", "1", "1", "1", "true"),
            ("testvo", "0", "0", "0", "0", "true"),
            ("testvo1", "5", "15", "20", "25", "false"),
            ("testvo2", "10", "20", "30", "40", "false"),
            ("testvo3@vo.ru", "1", "1", "1", "1", "true"),
            ("testvo4_vo", "0", "0", "0", "0", "false")
        ]

        for element in input_list:

            voname_field = driver.find_element_by_id('vo-config-add-field-vo')
            voname_field.clear()
            voname_field.send_keys(element[0])

            retries_field = driver.find_element_by_id('retry')
            retries_field.clear()
            retries_field.send_keys(element[1])

            globaltimeout_field = driver.find_element_by_id('global_timeout')
            globaltimeout_field.clear()
            globaltimeout_field.send_keys(element[2])

            queue_field = driver.find_element_by_id('max_time_queue')
            queue_field.clear()
            queue_field.send_keys(element[3])

            addsec_field = driver.find_element_by_id('sec_per_mb')
            addsec_field.clear()
            addsec_field.send_keys(element[4])


            showdn_field = driver.find_element_by_xpath('//tbody[@id="vo-config-add"][tr/td/select[@id="show_user_dn"]]')
            if element[5] == 'false':
                showdn_field.click()
                options = showdn_field.find_elements_by_tag_name("option")
                for option in options:
                    if option.get_attribute("value") == 'false':
                        option.click()
            elif element[5] == 'true':
                showdn_field.click()
                options = showdn_field.find_elements_by_tag_name("option")
                for option in options:
                    if option.get_attribute("value") == 'true':
                        option.click()


            button_add = driver.find_element_by_id('button_add_global')
            button_add.click()
            time.sleep(1)

        #CHECK IF EVERYTHING WAS SAVED
        check0_list = []
        check1_list = []

        count = 0
        page_list = driver.find_elements_by_xpath('//td[@class="vo_name"]')

        for elem in page_list:
            check0_list.append(elem.text)
        count = count + 1

        count = 0
        for element in input_list:
            check1_list.append(element[0])
        count = count + 1

        if not set(check1_list) < set(check0_list):
            return self.assertFalse("TEST: The retry wasn't saved", set(check1_list) - set(check0_list))

    def tearDown(self):
        self.driver.close()
        self.display.stop()

if __name__ == "__main__":
    unittest.main()

