.TH FTS-REST-CLI 1 "July 15, 2014" "fts-rest-snapshot"
.SH NAME
.PP
fts-rest-snapshot
.SH SYNOPIS
.PP
Usage: fts-rest-snapshot [options]
.SH DESCRIPTION
.PP
This command can be used to retrieve the internal status FTS3 has on all
pairs with ACTIVE transfers.
It allows to filter by VO, source SE and destination SE
.SH OPTIONS
.TP
.B -h/--help
Show this help message and exit
.RS
.RE
.TP
.B -v/--verbose
Verbose output.
.RS
.RE
.TP
.B -s/--endpoint
Fts3 rest endpoint.
.RS
.RE
.TP
.B -j/--json
Print the output in json format.
.RS
.RE
.TP
.B --key
The user certificate private key.
.RS
.RE
.TP
.B --cert
The user certificate.
.RS
.RE
.TP
.B --insecure
Do not validate the server certificate
.RS
.RE
.TP
.B --vo
Filter by vo
.RS
.RE
.TP
.B --source
Filter by source se
.RS
.RE
.TP
.B --destination
Filter by destination se
.RS
.RE
.SH EXAMPLE
.IP
.nf
\f[C]
$\ fts-rest-snapshot\ -s\ https://fts3-devel.cern.ch:8446
Source:\ \ \ \ \ \ \ \ \ \ \ \ \ \ gsiftp://whatever
Destination:\ \ \ \ \ \ \ \ \ gsiftp://whatnot
VO:\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ dteam
Max.\ Active:\ \ \ \ \ \ \ \ \ 5
Active:\ \ \ \ \ \ \ \ \ \ \ \ \ \ 1
Submitted:\ \ \ \ \ \ \ \ \ \ \ 0
Finished:\ \ \ \ \ \ \ \ \ \ \ \ 0
Failed:\ \ \ \ \ \ \ \ \ \ \ \ \ \ 0
Success\ ratio:\ \ \ \ \ \ \ -
Avg.\ Throughput:\ \ \ \ \ -
Avg.\ Duration:\ \ \ \ \ \ \ -
Avg.\ Queued:\ \ \ \ \ \ \ \ \ 0\ seconds
Most\ frequent\ error:\ -
\f[]
.fi
.SH AUTHORS
fts-devel\@cern.ch.
