.TH FTS-REST-CLI 1 "September 25, 2014" "fts-rest-delegate"
.SH NAME
.PP
fts-rest-delegate
.SH SYNOPIS
.PP
Usage: fts-rest-delegate [options]
.SH DESCRIPTION
.PP
This command can be used to (re)delegate your credentials to the FTS3
server
.SH OPTIONS
.TP
.B -h/--help
Show this help message and exit
.RS
.RE
.TP
.B -v/--verbose
Verbose output.
.RS
.RE
.TP
.B -s/--endpoint
FTS3 REST endpoint.
.RS
.RE
.TP
.B -j/--json
Print the output in json format.
.RS
.RE
.TP
.B --key
The user certificate private key.
.RS
.RE
.TP
.B --cert
The user certificate.
.RS
.RE
.TP
.B --insecure
Do not validate the server certificate
.RS
.RE
.TP
.B --access-token
Oauth2 access token (supported only by some endpoints, takes precedence)
.RS
.RE
.TP
.B -f/--force
Force the delegation
.RS
.RE
.SH EXAMPLE
.IP
.nf
\f[C]
$\ fts-rest-delegate\ -s\ https://fts3-devel.cern.ch:8446
Delegation\ id:\ 9a4257f435fa2010"
\f[]
.fi
.SH AUTHORS
fts-devel\@cern.ch.
