.TH FTS-REST-CLI 1 "September 25, 2014" "fts-rest-transfer-status"
.SH NAME
.PP
fts-rest-transfer-status
.SH SYNOPIS
.PP
Usage: fts-rest-transfer-status [options] JOB_ID
.SH DESCRIPTION
.PP
This command can be used to check the current status of a given job
.SH OPTIONS
.TP
.B -h/--help
Show this help message and exit
.RS
.RE
.TP
.B -v/--verbose
Verbose output.
.RS
.RE
.TP
.B -s/--endpoint
Fts3 rest endpoint.
.RS
.RE
.TP
.B -j/--json
Print the output in json format.
.RS
.RE
.TP
.B --key
The user certificate private key.
.RS
.RE
.TP
.B --cert
The user certificate.
.RS
.RE
.TP
.B --insecure
Do not validate the server certificate
.RS
.RE
.TP
.B --access-token
Oauth2 access token (supported only by some endpoints, takes precedence)
.RS
.RE
.SH EXAMPLE
.IP
.nf
\f[C]
$\ fts-rest-transfer-status\ -s\ https://fts3-devel.cern.ch:8446\ c079a636-c363-11e3-b7e5-02163e009f5a
Request\ ID:\ c079a636-c363-11e3-b7e5-02163e009f5a
Status:\ FINISHED
Client\ DN:\ /DC=ch/DC=cern/OU=Organic\ Units/OU=Users/CN=saketag/CN=678984/CN=Alejandro\ Alvarez\ Ayllon
Reason:
Submission\ time:\ 2014-04-13T23:31:34
Priority:\ 3
VO\ Name:\ dteam
\f[]
.fi
.SH AUTHORS
fts-devel\@cern.ch.
