.TH FTS-REST-CLI 1 "July 15, 2014" "fts-rest-transfer-cancel"
.SH NAME
.PP
fts-rest-transfer-cancel
.SH SYNOPIS
.PP
Usage: fts-rest-transfer-cancel [options]
.SH DESCRIPTION
.PP
This command can be used to cancel a running job.
It returns the final state of the canceled job.
Please, mind that if the job is already in a final state (FINISHEDDIRTY,
FINISHED, FAILED), this command will return this state.
.SH OPTIONS
.TP
.B -h/--help
Show this help message and exit
.RS
.RE
.TP
.B -v/--verbose
Verbose output.
.RS
.RE
.TP
.B -s/--endpoint
Fts3 rest endpoint.
.RS
.RE
.TP
.B -j/--json
Print the output in json format.
.RS
.RE
.TP
.B --key
The user certificate private key.
.RS
.RE
.TP
.B --cert
The user certificate.
.RS
.RE
.TP
.B --insecure
Do not validate the server certificate
.RS
.RE
.SH EXAMPLE
.IP
.nf
\f[C]
$\ fts-rest-transfer-cancel\ -s\ https://fts3-devel.cern.ch:8446\ c079a636-c363-11e3-b7e5-02163e009f5a
FINISHED
\f[]
.fi
.SH AUTHORS
fts-devel\@cern.ch.
