.\" Manpage for fts-rest-ban.
.\" Contact michal.simon@cern.ch to correct errors or typos.
.TH man 1 "20 May 2014" "1.0" "fts-rest-ban man page"
.SH NAME
fts-rest-ban
.SH SYNOPSIS
fts-rest-ban [options]
.SH DESCRIPTION
fts-rest-ban is a tool for banning and unbanning users and storage elements on a FTS3.
.SH OPTIONS
  -h, --help            show this help message and exit
  -v, --verbose         verbose output.
  -s ENDPOINT, --endpoint=ENDPOINT
                        FTS3 REST endpoint.
  -j, --json            print the output in JSON format.
  --key=UKEY            the user certificate private key.
  --cert=UCERT          the user certificate.
  --storage=STORAGE     storage element
  --user=USER_DN        user dn
  --unban               unban instead of ban
  --status=STATUS       status of the jobs that are already in the queue:
                        cancel or wait
  --timeout=TIMEOUT     the timeout for the jobs that are already in the queue
                        if status is wait
  --allow-submit        allow submissions if status is wait


.SH SEE ALSO
https://svnweb.cern.ch/trac/fts3/wiki/FTSRest
