.TH FTS-REST-CLI 1 "September 25, 2014" "fts-rest-ban"
.SH NAME
.PP
fts-rest-ban
.SH SYNOPIS
.PP
Usage: fts-rest-ban [options]
.SH DESCRIPTION
.PP
Ban and unban storage elements and users
.SH OPTIONS
.TP
.B -h/--help
Show this help message and exit
.RS
.RE
.TP
.B -v/--verbose
Verbose output.
.RS
.RE
.TP
.B -s/--endpoint
FTS3 REST endpoint.
.RS
.RE
.TP
.B -j/--json
Print the output in json format.
.RS
.RE
.TP
.B --key
The user certificate private key.
.RS
.RE
.TP
.B --cert
The user certificate.
.RS
.RE
.TP
.B --insecure
Do not validate the server certificate
.RS
.RE
.TP
.B --access-token
Oauth2 access token (supported only by some endpoints, takes precedence)
.RS
.RE
.TP
.B --storage
Storage element
.RS
.RE
.TP
.B --user
User dn
.RS
.RE
.TP
.B --unban
Unban instead of ban
.RS
.RE
.TP
.B --status
Status of the jobs that are already in the queue: cancel or wait
.RS
.RE
.TP
.B --timeout
The timeout for the jobs that are already in the queue if status is wait
.RS
.RE
.TP
.B --allow-submit
Allow submissions if status is wait
.RS
.RE
.SH EXAMPLE
.IP
.nf
\f[C]
$\ fts-rest-ban\ -s\ https://fts3-devel.cern.ch:8446\ --storage\ gsiftp://sample
No\ jobs\ affected
$\ fts-rest-ban\ -s\ https://fts3-devel.cern.ch:8446\ --storage\ gsiftp://sample\ --unban
$
\f[]
.fi
.SH AUTHORS
fts-devel\@cern.ch.
