#!/usr/bin/python
import unittest, time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from pyvirtualdisplay import Display

class FTS3develSeTab(unittest.TestCase):

    def setUp(self):
        self.display = Display(visible=0, size=(800, 600))
        self.display.start()
        profile = webdriver.FirefoxProfile('/home/jenkins/.mozilla/firefox/browser/default/jenkins')
        self.driver = webdriver.Firefox(profile)

    def test_save_bad_activity(self):
        """
        Try to save bad values
        """
        driver = self.driver
        driver.get("https://fts3-devel.cern.ch:8446/config/activity_shares")

        #SET UP
        setup_list = [
            ("savebadvo", [("activity0", "0.3")]),
            ("savebadvo1", [("activity1", "0.56")]),
            ("savebadvo2", [("activity2", "0.5")]),
            ("savebadvo3", [("activity3", "0.2")]),
            ("savebadvo4", [("activity4", "0.99")]),
            ("savebadvo5", [("activity5", "0.98")])
        ]

        compare_list =[]	
        for element in setup_list:
            count = 0
            vo_field = driver.find_element_by_id('activity-share-add-field-vo')
            vo_field.clear()
            vo_field.send_keys(element[0])

            for elem in element[1]:
                compare_list.append(element[0])
                compare_list.append(elem[0])
                compare_list.append(elem[1])
                activity_field = driver.find_element_by_id('activity-share-add-field-share-name')
                activity_field.clear()
                activity_field.send_keys(elem[0])

                weight_field = driver.find_element_by_id('activity-share-add-field-share-value')
                weight_field.send_keys(Keys.CONTROL + 'a')
                weight_field.send_keys(Keys.BACKSPACE)
                weight_field.send_keys(elem[1])

                plus = driver.find_element_by_id('activity-share-add-entry-btn')
                plus.click()

            button_add = driver.find_element_by_id('button-add')
            button_add.click()
            count = count+1
            time.sleep(1)

        driver.refresh()

        #CHECK IF EVERYTHING WAS SAVED
        check0_list = []
        check1_list = []

        count = 0
        page_list = driver.find_elements_by_xpath('//h2[@class="panel-title"]')

        for elem in page_list:
            check0_list.append(elem.text)
        count = count + 1

        count = 0
        for element in setup_list:
            check1_list.append(element[0])
        count = count + 1

        if not set(check1_list) < set(check0_list):
            return self.assertFalse("TEST: The activity share wasn't saved", set(check1_list) - set(check0_list))

        inputs_list = []
        for element in check1_list:
            for elem in driver.find_elements_by_xpath('//h2[@class="panel-title"]'):
                if elem.text == element:
                    input_name = '//form[@name="' +element + '"]//input'
                    inputs = driver.find_elements_by_xpath(input_name)
                    for inp in inputs:
                        if inp.get_attribute("value")!="":
                            inputs_list.append(inp.get_attribute('value'))

        if set(inputs_list) < set(compare_list):
            return self.assertFalse("TEST: The activity share parameter wasn't saved", set(inputs_list) - set(compare_list))



        # TEST test_save_good_activity
        save_list = [
            ("savebadvo", [("activity0", "7")]),
            ("savebadvo1", [("activity1", "-67")]),
            ("savebadvo2", [("activity2", "abc")]),
            ("savebadvo3", [("activity3", "$")]),
            ("savebadvo4", [(" ", "0.99")]),
            ("savebadvo5", [("", "0.98")])

        ]

        #SAVE
        compare_list = []
        for element, el in zip(save_list, setup_list):
            count = 0
            panel = '//div[@name="panel_' +element[0] + '"][@class="panel panel-info"]' 
            panel_f = driver.find_element_by_xpath(panel)

            if panel_f.get_attribute("name") == 'panel_'+element[0]:
                for elem in element[1]:

                    compare_list.append(element[1][count][1])

                    activity_field = driver.find_element_by_xpath('//div[@name="panel_' +element[0] + '"]//input[@value="'+el[1][count][0]+'"]')
                    activity_field.clear()
                    activity_field.send_keys(elem[0])

                    weight_field = driver.find_element_by_xpath('//div[@name="panel_' +element[0] + '"]//input[@value="'+el[1][count][1]+'"]')
                    weight_field.send_keys(Keys.CONTROL + 'a')
                    weight_field.send_keys(Keys.BACKSPACE)
                    weight_field.send_keys(elem[1])

                    count = count + 1
                btn = '//button[@name="save_' +element[0] + '"][@class="btn btn-primary"]'
                button_save = driver.find_element_by_xpath(btn)
                button_save.click()

        driver.refresh()

        #CHECK IF BUG WAS SAVED
        inputs_list = []
        for element in save_list:
            for elem in driver.find_elements_by_xpath('//div[@id="activity-shares-list"]//h2[@class="panel-title"]'):
                if elem.text == element[0]:
                    input_name = '//form[@name="' +element[0] + '"]//input[@name="weight"]'
                    inputs = driver.find_elements_by_xpath(input_name)
                    for inp in inputs:
                        if inp.get_attribute('value') != '':		        
                            inputs_list.append(inp.get_attribute('value'))

        if set(compare_list)&set(inputs_list):
            return self.assertFalse("TEST: The activity share parameter WAS saved", set(compare_list)&set(inputs_list))


    def tearDown(self):
        self.driver.close()
        self.display.stop()

if __name__ == "__main__":
    unittest.main()

