#!/usr/bin/python
import unittest, time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from pyvirtualdisplay import Display

class FTS3develSeTab(unittest.TestCase):

    def setUp(self):
        self.display = Display(visible=0, size=(800, 600))
        self.display.start()
        profile = webdriver.FirefoxProfile('/home/jenkins/.mozilla/firefox/browser/default/jenkins')
        self.driver = webdriver.Firefox(profile)

    def test_add_good_activity(self):
        """
        Test add new activity shares
        """
        driver = self.driver
        driver.get("https://fts3-devel.cern.ch:8446/config/activity_shares")

        input_list = [
            ("testvo", [("activity", "0.3")]),
            ("testvo1", [("activity1", "0.56"), ("activity1_1", "0.9"), ("activity1_2", "0.34")]),
            ("testvo2", [("activity2", "0")])
        ]

        compare_list =[]	
        for element in input_list:
            count = 0
            vo_field = driver.find_element_by_id('activity-share-add-field-vo')
            vo_field.clear()
            vo_field.send_keys(element[0])

            for elem in element[1]:
                compare_list.append(element[0])
                compare_list.append(elem[0])
                compare_list.append(elem[1])
                activity_field = driver.find_element_by_id('activity-share-add-field-share-name')
                activity_field.clear()
                activity_field.send_keys(elem[0])

                weight_field = driver.find_element_by_id('activity-share-add-field-share-value')
                weight_field.send_keys(Keys.CONTROL + 'a')
                weight_field.send_keys(Keys.BACKSPACE)
                weight_field.send_keys(elem[1])

                plus = driver.find_element_by_id('activity-share-add-entry-btn')
                plus.click()

            button_add = driver.find_element_by_id('button-add')
            button_add.click()
            count = count+1
            time.sleep(1)

        #CHECK IF EVERYTHING WAS SAVED
        check0_list = []
        check1_list = []

        count = 0
        page_list = driver.find_elements_by_xpath('//h2[@class="panel-title"]')

        for elem in page_list:
            check0_list.append(elem.text)
        count = count + 1

        count = 0
        for element in input_list:
            check1_list.append(element[0])
        count = count + 1

        if not set(check1_list) < set(check0_list):
            return self.assertFalse("TEST: The activity share wasn't saved", set(check1_list) - set(check0_list))

        inputs_list = []
        for element in check1_list:
            for elem in driver.find_elements_by_xpath('//h2[@class="panel-title"]'):
                if elem.text == element:
                    input_name = '//form[@name="' +element + '"]//input'
                    inputs = driver.find_elements_by_xpath(input_name)
                    for inp in inputs:
                        if inp.get_attribute("value")!="":
                            inputs_list.append(inp.get_attribute('value'))

        if set(inputs_list) < set(compare_list):
            return self.assertFalse("TEST: The activity share parameter was NOT saved", set(inputs_list) - set(compare_list))



    def tearDown(self):
        self.driver.close()
        self.display.stop()

if __name__ == "__main__":
    unittest.main()

