#!/usr/bin/python
import unittest, time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from pyvirtualdisplay import Display

class FTS3develSeTab(unittest.TestCase):

    def setUp(self):
        self.display = Display(visible=0, size=(800, 600))
        self.display.start()
        profile = webdriver.FirefoxProfile('/home/jenkins/.mozilla/firefox/browser/default/jenkins')
        self.driver = webdriver.Firefox(profile)

    def test_add_bad_activity(self):
        """
        Test add bad values 
        """
        driver = self.driver
        driver.get("https://fts3-devel.cern.ch:8446/config/activity_shares")

        input_list = [
            ("", [("", "")]),
            (" ", [("", "")]),
            ("badvo2", [("activity3", "3")]),
            ("badvo3", [("activity4", "$")]),
            ("badvo4", [("activity5", "abc")]),
            ("badvo5", [("activity2_1", "0.9"), ("activity2", "-100")]),
            ("badvo6", [(" ", "0.9")]),
            ("badvo7", [("", "0.9")])
        ]

        compare_list =[]
        for element in input_list:

            vo_field = driver.find_element_by_id('activity-share-add-field-vo')
            vo_field.clear()
            vo_field.send_keys(element[0])

            for elem in element[1]:
                compare_list.append(element[0])
                compare_list.append(elem[0])
                compare_list.append(elem[1])
                activity_field = driver.find_element_by_id('activity-share-add-field-share-name')
                activity_field.clear()
                activity_field.send_keys(elem[0])

                weight_field = driver.find_element_by_id('activity-share-add-field-share-value')
                weight_field.send_keys(Keys.CONTROL + 'a')
                weight_field.send_keys(Keys.BACKSPACE)
                weight_field.send_keys(elem[1])

                plus = driver.find_element_by_id('activity-share-add-entry-btn')
                plus.click()

            button_add = driver.find_element_by_id('button-add')
            button_add.click()
            time.sleep (1)
            if not driver.find_elements_by_id('activity-share-delete-entry-btn'):
                pass
            else:
                for i in driver.find_elements_by_id('activity-share-delete-entry-btn'):
                    i.click()


        driver.refresh()
        time.sleep(1)

        #CHECK IF BUG WAS SAVED
        inputs_list = []
        for element in input_list:
            for elem in driver.find_elements_by_xpath('//div[@id="activity-shares-list"]//h2[@class="panel-title"]'):
                if elem.text == element[0]:
                    input_name = '//form[@name="' +element[0] + '"]//input'
                    inputs = driver.find_elements_by_xpath(input_name)
                    for inp in inputs:
                        if inp.get_attribute('value') != '':		        
                            inputs_list.append(inp.get_attribute('value'))

        if set(compare_list)&set(inputs_list):
            return self.assertFalse("TEST: The activity share parameter WAS saved", set(compare_list)&set(inputs_list))

    def tearDown(self):
        self.driver.close()
        self.display.stop()

if __name__ == "__main__":
    unittest.main()

